### ISSUE TITLE
how to configure system- config.js for ngrx/store 2.2.1

### ISSUE THREAD

**Issue by sergio11** [ngrx/store#223]
Hi, 

I'm using Angular 2.0.0 and have the system- config.js configured as follows

```
/** Map relative paths to URLs. */
const map: any = {
  'app': 'src/app',
  'main': 'main.js',
  '@angular/core': 'vendor/@angular/core/bundles/core.umd.js',
  '@angular/common': 'vendor/@angular/common/bundles/common.umd.js',
  '@angular/compiler': 'vendor/@angular/compiler/bundles/compiler.umd.js',
  '@angular/platform-browser': 'vendor/@angular/platform-browser/bundles/platform-browser.umd.js',
  '@angular/platform-browser-dynamic': 'vendor/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
  '@angular/http': 'vendor/@angular/http/bundles/http.umd.js',
  '@angular/router': 'vendor/@angular/router/bundles/router.umd.js',
  '@angular/forms': 'vendor/@angular/forms/bundles/forms.umd.js',
  'ng2-bootstrap': 'vendor/ng2-bootstrap',
  'ng2-translate': 'vendor/ng2-translate',
  'angular2-fontawesome': 'vendor/angular2-fontawesome',
  '@ngrx': 'vendor/@ngrx',
  'moment': 'vendor/moment/min/moment.min.js'
};

/** User packages configuration. */
const packages: any = {
  'app': {main: 'main', defaultExtension: 'js'},
  'rxjs': {main: 'Rx.js', defaultExtension: 'js'},
  'ng2-bootstrap': { defaultExtension: 'js' },
  'ng2-translate': { defaultExtension: 'js' },
  'angular2-fontawesome': { defaultExtension: 'js' },
  '@ngrx/core': {
    main: 'index.js',
    format: 'cjs'
  },
  '@ngrx/store': {
    main: 'index.js',
    format: 'cjs'
  },
  '@ngrx/effects': {
    main: 'index.js',
    format: 'cjs'
  }
};


////////////////////////////////////////////////////////////////////////////////////////////////
/***********************************************************************************************
 * Everything underneath this line is managed by the CLI.
 **********************************************************************************************/
const barrels: string[] = [
  // Angular specific barrels.
  '@angular/core',
  '@angular/common',
  '@angular/compiler',
  '@angular/forms',
  '@angular/http',
  '@angular/router',
  '@angular/platform-browser',
  '@angular/platform-browser-dynamic',
  // Thirdparty barrels.
  'rxjs',
  // App specific barrels.
  'app/',
  'app/components/',
  'app/components/+home/',
  'app/components/header',
  'app/components/shared',
  'app/accounts/',
  'app/accounts/+login/',
  'app/accounts/+signup/'

  /** @cli-barrel */
];

const cliSystemConfigPackages: any = {};
barrels.forEach((barrelName: string) => {
  cliSystemConfigPackages[barrelName] = { main: 'index' };
});

/** Type declaration for ambient System. */
declare var System: any;

// Apply the CLI SystemJS configuration.
System.config({
  map: {
    '@angular': 'vendor/@angular',
    'rxjs': 'vendor/rxjs',
    'main': 'main.js'
  },
  packages: cliSystemConfigPackages
});

// Apply the user's configuration.
System.config({ map, packages });
```

but to launch the application I get the following error from @ngrx/store/index.js

```

zone.js:344 Unhandled Promise rejection: SyntaxError: Unexpected token export
        at Object.eval (http://localhost:4200/app/app.module.js:14:15)
        at eval (http://localhost:4200/app/app.module.js:53:4)
        at eval (http://localhost:4200/app/app.module.js:54:3)
    Evaluating http://localhost:4200/vendor/@ngrx/store/index.js
    Evaluating http://localhost:4200/app/app.module.js
    Evaluating http://localhost:4200/app/index.js
    Evaluating http://localhost:4200/main.js
    Error loading http://localhost:4200/main.js ; Zone: <root> ; Task: Promise.then ; Value: Error: SyntaxError: Unexpected token export(…) nullconsoleError @ zone.js:344
zone.js:346 Error: Uncaught (in promise): Error: SyntaxError: Unexpected token export(…)
```

This is my version of @ngrx/store

```
BISITE@bisite ~/Documents/projects/photogram: npm list @ngrx/store
instangular@0.0.0 /Users/BISITE/Documents/projects/photogram
└── @ngrx/store@2.2.1 
```

Can you tell me what is the current way of doing the mapping?

thanks.

**Comment by kylecordes** [comment]
ngrx/store and /core now ship UMDs which work just like the Angular core/common/http/etc UMDs. You can use the same kind of System setup as you use for those - visible in your snippet above.

**Comment by sergio11** [comment]
you mean like this:

```
'@ngrx/core': 'vendor/@ngrx/core/bundles/core.min.umd.js',
'@ngrx/store': 'vendor/@ngrx/store/bundles/store.min.umd.js',
'@ngrx/effects': 'vendor/@ngrx/effects',
```

but I get the following error:

```
zone.js:1263 GET http://localhost:4200/vendor/@ngrx/core/bundles/core.min.umd.js/add/operator/select 404 (Not Found)scheduleTask @ zone.js:1263ZoneDelegate.scheduleTask @ zone.js:205Zone.scheduleMacroTask @ zone.js:142(anonymous function) @ zone.js:1293send @ VM208:3fetchTextFromURL @ system.src.js:1156(anonymous function) @ system.src.js:1739ZoneAwarePromise @ zone.js:467(anonymous function) @ system.src.js:1738(anonymous function) @ system.src.js:2764(anonymous function) @ system.src.js:3338(anonymous function) @ system.src.js:3605(anonymous function) @ system.src.js:3990(anonymous function) @ system.src.js:4453(anonymous function) @ system.src.js:4705(anonymous function) @ system.src.js:408ZoneDelegate.invoke @ zone.js:192Zone.run @ zone.js:85(anonymous function) @ zone.js:451ZoneDelegate.invokeTask @ zone.js:225Zone.runTask @ zone.js:125drainMicroTaskQueue @ zone.js:357ZoneTask.invoke @ zone.js:297
zone.js:344 Unhandled Promise rejection: Error: XHR error (404 Not Found) loading http://localhost:4200/vendor/@ngrx/core/bundles/core.min.umd.js/add/operator/select
        at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:4200/vendor/zone.js/dist/zone.js:636:29)
        at ZoneDelegate.invokeTask (http://localhost:4200/vendor/zone.js/dist/zone.js:225:37)
        at Zone.runTask (http://localhost:4200/vendor/zone.js/dist/zone.js:125:47)
        at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/vendor/zone.js/dist/zone.js:293:33)
    Error loading http://localhost:4200/vendor/@ngrx/core/bundles/core.min.umd.js/add/operator/select as "@ngrx/core/add/operator/select" from http://localhost:4200/app/accounts/+login/login.selector.js ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: XHR error (404 Not Found) loading http://localhost:4200/vendor/@ngrx/core/bundles/core.min.umd.js/add/operator/select(…) nullconsoleError @ zone.js:344_loop_1 @ zone.js:371drainMicroTaskQueue @ zone.js:375ZoneTask.invoke @ zone.js:297
zone.js:346 Error: Uncaught (in promise): Error: Error: XHR error (404 Not Found) loading http://localhost:4200/vendor/@ngrx/core/bundles/core.min.umd.js/add/operator/select(…)
```

You could give me a snippet of code to see how it should be configured please?

thanks for answering

**Comment by costasovo** [comment]
I've had similar problem. I think it can be some bug UMD. This worked for me:

``` /**
 * System configuration for Angular 2 samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      app: 'app',

      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      '@ngrx': 'npm:@ngrx',

      // other libraries
      'rxjs':                       'npm:rxjs',
      'angular2-in-memory-web-api': 'npm:angular2-in-memory-web-api',
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js'
      },
      rxjs: {
        defaultExtension: 'js'
      },
      'angular2-in-memory-web-api': {
        main: './index.js',
        defaultExtension: 'js'
     },
    '@ngrx/core': {
            main: 'bundles/core.umd.js',
            format: 'cjs'
     },
     '@ngrx/store': {
            main: 'bundles/store.umd.js',
            format: 'cjs'
     },
     '@ngrx/store-devtools': {
            main: 'bundles/store-devtools.umd.js',
            format: 'cjs'
     },
    '@ngrx/store-log-monitor': {
            main: 'bundles/store-log-monitor.umd.js',
            format: 'cjs'
        }
     }
  });
})(this);
```

**Comment by sergio11** [comment]
thanks @costasovo, It worked!!
