### ISSUE TITLE
Cannot run inside ts-node

### ISSUE THREAD

**Issue by xban1x** [ngrx/store#419]
Trying to run isomorphic app inside ts-node gives this error.

`/Users/xban1x/Code/reveel/landingpage/node_modules/@ngrx/store/src/ng2.js:7
import { OpaqueToken, NgModule } from '@angular/core';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/xban1x/Code/reveel/landingpage/dist/ngfactory/src/app/app.server.module.ngfactory.ts:17:1)
    at Module._compile (module.js:571:32)`

**Comment by z3v0k** [comment]
+1

**Comment by nschipperbrainsmith** [comment]
Same problem here using NodeJS version 6.10.1 export statements seem to work fine import statements however are not allowed / working yet it seems. Did @xban1x you find any solution for working around the problem above in the server rendered  application environment?

**Comment by IliaIdakiev** [comment]
+1

**Comment by nschipperbrainsmith** [comment]
What I ended up doing was within the generated factories replace all the import statements from `ngrx/store/<<some sub path>>` to `ngrx/store` this has fixed it. Though I've got no clue how theses came about in the first place as they are seemingly added by the AOT compiler as they are not part of my own code.

**Comment by robwormald** [comment]
Please check this against NgRx v4, and if it’s still an issue, please reopen on https://github.com/ngrx/platform. Thanks!
